Copied readme example to new examples directory and adjusted formatti…
markcampanelli/pvfit pull request #2
Opened 2019-08-14 14:45 UTC by bt-

…ng to wrap lines.

I've never made a pull request, so this one is as much to understand how it works as making any useful contribution.

I just created a script file from the readme example and also wrapped the lines.  I was having a little trouble following along while having to scroll left and right.

2019-08-14 18:45 UTC, markcampanelli requested changes
Thanks for the quick contribution :). I'm using GitHub's PR review system here, and I'm requesting a couple small changes. Also, can you change the filename from `pvfit-m_ex.py` to `getting_started.py`?

I like the 80 char column limit for the example files, but note that I use a 120 char limit for source code. (Of course, I need to document all this in the README.)

I will be doing a round of further documentation shortly, and I plan to improve this getting started example (showing how to load actual numpy data and compute individual integrals for closer examination) and I will change the README to refer to running this script instead of typing it out there.

2019-08-14 18:45 UTC, markcampanelli commented on examples/pvfit-m_ex.py
> +# pvfit_m has several data classes that wrap underlying numpy.ndarray data
Remove redundant `#` .

2019-08-14 18:45 UTC, markcampanelli commented on examples/pvfit-m_ex.py
> +# For example, assuming one has loaded wavelength and spectral responsivity
Remove redundant `#` s in this line and previous.

2019-08-15 15:53 UTC, bt- commented
@markcampanelli, I made the adjustments you requested.  Let me know if you have any other comments.  I was thinking it might be helpful to have an example in an ipynb as well.

2019-08-15 20:46 UTC, markcampanelli approved these changes
Thanks!

2019-08-15 20:46 UTC, merged